# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run ci:test
      - run:
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  ci:
    jobs:
      - test
        filters:
          branches:
            only:
              - master
              - develop
              - develop/v1